name: Build and deploy container app to Azure Web App - ropoflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_7523dc3b6ca54da4937113e93ade72c2 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_abe4624f5e254ccc89e444836c7f8316 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            desarrolloropofy/n8n-custom:latest
            desarrolloropofy/n8n-custom:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ropoflow'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5cb3bb19953741dea659eef6c69ba38c }}
          images: 'desarrolloropofy/n8n-custom:${{ github.sha }}'
